# https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
# Name of the workflow
name: My Test Workflow

# define the trigger events
on: [push]

# jobs run in parallel by default, each runs steps in sequence
jobs:
    # job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, Gitub Actions!"
