# https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
# Name of the workflow
name: My Test Workflow

# define the trigger events
on: [push]

# jobs run in parallel by default, each runs steps in sequence
jobs:
    # job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - name: Say hello
            run: echo "Hello, Gitub Actions!"
    
    # Jobs to build and test out C code
    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-lates
        steps:
            # Use github.com/actions/checkoout to checkout this repo
          - name: Check out this repo
            uses: actions/checkout@v3

            # install necessary packages
          - name: Install dependencies
            run: sudo apt install -y build-essential python3
            
            # show present working directory
          - run: pwd

        # run python test script
          - name: Run test
            run: python3 test.py

